server:
  port: ${PORT}
spring:
  application:
    name: bynails-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/bynailsdb
      auto-index-creation: true

jwt:
  secret: ${SECRET}
  expiration: 36000000
